create table
public.ml_storage (
    id integer generated by default as identity,
    sku text not null,
    mls integer null default 0,
    num_blue_ml integer null default 0,
    constraint ml_storage_pkey primary key (id)
  ) tablespace pg_default;

create table
public.gold_tracker (
    gold integer null default 100,
)tablespace pg_default;


create table
  public.potion_storage (
    sku text not null,
    name text not null,
    red_ml integer not null default 0,
    green_ml integer not null default 0,
    blue_ml integer not null default 0,
    dark_ml integer not null default 0,
    quantity integer not null default 0,
    cost integer not null default 0,
    id integer generated by default as identity,
    constraint potion_storage_pkey primary key (id)
  ) tablespace pg_default;



create table
  public.carts (
    id integer generated by default as identity,
    customer_name text not null,
    constraint carts_pkey primary key (id),
    constraint carts_id_key unique (id)
  ) tablespace pg_default;

create table
  public.cart_line_items (
    cart_id integer not null,
    sku text null,
    count_to_buy integer not null,
    items_quantity integer generated by default as identity,
    constraint cart_line_items_pkey primary key (cart_id)
  ) tablespace pg_default;